From ca31cdaf61fd6865091aacb4e9768d5650360d46 Mon Sep 17 00:00:00 2001
From: Vishesh Handa <me@vhanda.in>
Date: Thu, 3 Apr 2014 15:10:57 +0200
Subject: [PATCH 47/48] XapianSearchStore: Catch some more exceptions

---
 src/xapian/xapiansearchstore.cpp | 9 ++++++++-
 1 file changed, 8 insertions(+), 1 deletion(-)

diff --git a/src/xapian/xapiansearchstore.cpp b/src/xapian/xapiansearchstore.cpp
index 59c035b..0edf99a 100644
--- a/src/xapian/xapiansearchstore.cpp
+++ b/src/xapian/xapiansearchstore.cpp
@@ -46,12 +46,19 @@ void XapianSearchStore::setDbPath(const QString& path)
     m_dbPath = path;
 
     delete m_db;
+    m_db = 0;
+
     try {
         m_db = new Xapian::Database(m_dbPath.toUtf8().constData());
     }
     catch (const Xapian::DatabaseOpeningError&) {
         kError() << "Xapian Database does not exist at " << m_dbPath;
-        m_db = 0;
+    }
+    catch (const Xapian::DatabaseCorruptError&) {
+        kError() << "Xapian Database corrupted at " << m_dbPath;
+    }
+    catch (...) {
+        kError() << "Random exception, but we do not want to crash";
     }
 }
 
-- 
1.9.1

